spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:graphql;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true


logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace